services:
  mytodo:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: mytodo:dev
    container_name: onepiece
    volumes:
      - ./:/app
    ports:
      - "3000:3000"