services:
  onepiece:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: onepiece:dev
    container_name: onepiece
    volumes:
      - ./:/app
    ports:
      - "3000:3000"